/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ['@rdlabo/eslint-rules'],
  rules: {
    '@rdlabo/eslint-rules/example-rule': 'error',
  },
};
