import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { ESLint } from 'eslint';
import { pluginId } from './plugin-id';
import { rules } from './rules';

const filePath = resolve(__dirname, '../../src/configs/recommended.ts');
const rawContent = `/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ["${pluginId}"],
  rules: {
    ${rules
      .filter((rule) => rule.recommended)
      .map((rule) => `"${rule.id}": "error"`)
      .join(',\n    ')}
  },
};
`;
const engine = new ESLint({ fix: true });
engine.lintText(rawContent, { filePath }).then((lintResult) => {
  const content = lintResult[0].output || rawContent;
  writeFileSync(filePath, content);
});
