import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { ESLint } from 'eslint';
import { rules } from './rules';

const filePath = resolve(__dirname, '../../src/index.ts');
const rawContent = `/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: import("./configs/recommended"),
  },
  rules: {
    ${rules
      .map((rule) => `"${rule.name}": import("./rules/${rule.name}")`)
      .join(',\n    ')}
  },
};
`;
const engine = new ESLint({ fix: true });
engine.lintText(rawContent, { filePath }).then((lintResult) => {
  const content = lintResult[0].output || rawContent;
  writeFileSync(filePath, content);
});
